=== gramaziokohler/antikythera/src/antikythera/models/blueprint.v1.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/gramaziokohler/antikythera/refs/heads/main/src/antikythera/models/blueprint.v1.schema.json",
    "title": "Antikythera Blueprint",
    "description": "Schema for Antikythera Blueprint files",
    "type": "object",
    "required": [
        "id",
        "name",
        "version"
    ],
    "properties": {
        "id": {
            "type": "string",
            "description": "Unique identifier for the blueprint"
        },
        "name": {
            "type": "string",
            "description": "A human-readable name for the blueprint"
        },
        "version": {
            "type": "string",
            "description": "The version of the blueprint schema"
        },
        "description": {
            "type": "string",
            "description": "A human-readable description of the blueprint"
        },
        "tasks": {
            "type": "array",
            "description": "A list of tasks that make up the blueprint",
            "items": {
                "$ref": "#/definitions/Task"
            }
        }
    },
    "definitions": {
        "Task": {
            "type": "object",
            "required": [
                "id",
                "type"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Unique identifier for the task"
                },
                "type": {
                    "type": "string",
                    "description": "The type of the task"
                },
                "description": {
                    "type": "string",
                    "description": "A human-readable description of the task"
                },
                "condition": {
                    "type": "string",
                    "description": "A condition expression for the task execution"
                },
                "inputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaskInput"
                    }
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaskOutput"
                    }
                },
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TaskParam"
                    }
                },
                "depends_on": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Dependency"
                    }
                },
                "state": {
                    "$ref": "#/definitions/TaskState"
                }
            }
        },
        "TaskInput": {
            "allOf": [
                {
                    "$ref": "#/definitions/TaskIO"
                },
                {
                    "properties": {
                        "get_from": {
                            "type": "string",
                            "description": "Key to retrieve the input value from"
                        }
                    }
                }
            ]
        },
        "TaskOutput": {
            "allOf": [
                {
                    "$ref": "#/definitions/TaskIO"
                },
                {
                    "properties": {
                        "set_to": {
                            "type": "string",
                            "description": "Key to set the output value to"
                        }
                    }
                }
            ]
        },
        "TaskParam": {
            "$ref": "#/definitions/TaskIO"
        },
        "TaskIO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Name of the IO item"
                },
                "value": {
                    "description": "Value of the IO item (can be any type)"
                },
                "type": {
                    "type": "string",
                    "description": "Type of the IO item"
                },
                "description": {
                    "type": "string",
                    "description": "Description of the IO item"
                }
            }
        },
        "Dependency": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "description": "ID of the task to depend on"
                },
                "type": {
                    "$ref": "#/definitions/DependencyType"
                }
            }
        },
        "DependencyType": {
            "type": "string",
            "enum": [
                "FS",
                "FF",
                "SS",
                "SF"
            ],
            "default": "FS"
        },
        "TaskState": {
            "type": "string",
            "enum": [
                "PENDING",
                "READY",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "SKIPPED",
                "UNSPECIFIED"
            ],
            "default": "PENDING"
        }
    }
}

=== gramaziokohler/antikythera/toy_problem_8.json
{
    "version": "1.0",
    "id": "toy-problem-8",
    "name": "Toy Problem 8",
    "description": "Conditional execution based on previous result",
    "tasks": [
        {
            "id": "start",
            "type": "system.start",
            "outputs": [
                {
                    "name": "process_start_time",
                    "type": "timestamp"
                }
            ]
        },
        {
            "id": "A1-ask-user",
            "type": "user_prompt.confirm",
            "params": [
                {
                    "name": "message",
                    "value": "Do you want to proceed?"
                },
                {
                    "name": "options",
                    "value": [
                        "Yes",
                        "No"
                    ]
                }
            ],
            "outputs": [
                {
                    "name": "result",
                    "type": "str"
                }
            ],
            "depends_on": [
                {
                    "id": "start"
                }
            ]
        },
        {
            "id": "A1-extra",
            "type": "user_prompt.confirm",
            "description": "Conditional prompt that only runs if user said Yes",
            "condition": "decision == 'Yes'",
            "params": [
                {
                    "name": "message",
                    "value": "You chose Yes. Are you absolutely sure?"
                },
                {
                    "name": "options",
                    "value": [
                        "I am sure",
                        "Actually no"
                    ]
                }
            ],
            "inputs": [
                {
                    "name": "decision",
                    "type": "str",
                    "get_from": "result"
                }
            ],
            "outputs": [
                {
                    "name": "result",
                    "type": "str",
                    "set_to": "result_extra"
                }
            ],
            "depends_on": [
                {
                    "id": "A1-ask-user"
                }
            ]
        },
        {
            "id": "A2",
            "type": "system.sleep",
            "description": "Sleep for 5 seconds",
            "params": [
                {
                    "name": "duration",
                    "value": 5
                }
            ],
            "depends_on": [
                {
                    "id": "start"
                }
            ]
        },
        {
            "id": "B1",
            "type": "user_interaction.user_output",
            "description": "Print result",
            "inputs": [
                {
                    "name": "result",
                    "type": "str"
                },
                {
                    "name": "extra_info",
                    "type": "str",
                    "get_from": "result_extra",
                    "value": "N/A"
                },
                {
                    "name": "frame_world_xy",
                    "value": {
                        "dtype": "compas.geometry/Frame",
                        "data": {
                            "point": [
                                0.0,
                                0.0,
                                0.0
                            ],
                            "xaxis": [
                                1.0,
                                0.0,
                                0.0
                            ],
                            "yaxis": [
                                0.0,
                                1.0,
                                0.0
                            ]
                        },
                        "guid": "55982853-464f-49f0-a85a-f5a4a8b11de7"
                    }
                }
            ],
            "depends_on": [
                {
                    "id": "A1-extra",
                    "type": "FS"
                },
                {
                    "id": "A2",
                    "type": "FS"
                }
            ]
        },
        {
            "id": "end",
            "type": "system.end",
            "outputs": [
                {
                    "name": "process_end_time",
                    "type": "timestamp"
                }
            ],
            "depends_on": [
                {
                    "id": "B1"
                }
            ]
        }
    ]
}

=== gramaziokohler/antikythera/toy_problem_0.json
{
  "version": "1.0",
  "id": "toy-problem-0",
  "name": "Toy Problem 0",
  "description": "Simplest possible blueprint",
  "tasks": [
    {
      "id": "start",
      "type": "system.start",
      "outputs": [
        {
          "name": "process_start_time",
          "type": "timestamp"
        }
      ]
    },
    {
      "id": "A1",
      "type": "system.sleep",
      "description": "Sleep for 5 seconds",
      "params": [
        {
          "name": "duration",
          "value": 5
        }
      ],
      "depends_on": [
        {
          "id": "start"
        }
      ]
    },
    {
      "id": "A2",
      "type": "user_interaction.user_output",
      "description": "Print result",
      "inputs": [
        {
          "name": "process_start_time",
          "type": "timestamp"
        }
      ],
      "depends_on": [
        {
          "id": "A1"
        }
      ]
    },
    {
      "id": "end",
      "type": "system.end",
      "outputs": [
        {
          "name": "process_end_time",
          "type": "timestamp"
        }
      ],
      "depends_on": [
        {
          "id": "A2"
        }
      ]
    }
  ]
}

=== gramaziokohler/antikythera/toy_problem_6_inner.json
{
    "version": "1.0",
    "id": "TP6-inner",
    "name": "Toy Problem 6 Inner",
    "description": "Inner blueprint for Toy Problem 6 to print element guids",
    "tasks": [
        {
            "id": "start",
            "type": "system.start",
            "outputs": [
                {
                    "name": "process_start_time",
                    "type": "timestamp"
                }
            ]
        },
        {
            "id": "A1",
            "type": "user_interaction.user_output",
            "description": "Print element ID",
            "inputs": [
                {
                    "name": "element",
                    "type": "dict"
                }
            ],
            "outputs": [
                {
                    "name": "result",
                    "type": "str"
                }
            ],
            "depends_on": [
                {
                    "id": "start"
                }
            ]
        },
        {
            "id": "end",
            "type": "system.end",
            "outputs": [
                {
                    "name": "process_end_time",
                    "type": "timestamp"
                }
            ],
            "depends_on": [
                {
                    "id": "A1"
                }
            ]
        }
    ]
}
